In [2]:
import cv2
import numpy

In [3]:
import glob2
glob2.glob("files\\*")

['files\\IMG_20181219_131553.jpg',
 'files\\supermarkets-commas.txt',
 'files\\supermarkets-semi-colons.txt',
 'files\\supermarkets.csv',
 'files\\supermarkets.json',
 'files\\supermarkets.xlsx']

In [4]:
im = cv2.imread("files\\IMG_20181219_131553.jpg",1)

In [5]:
cv2.imwrite('test.jpg',im)

True

In [6]:
print(im)

[[[ 20  35  61]
  [ 16  31  57]
  [ 14  29  55]
  ...
  [ 61  88 115]
  [ 64  91 118]
  [ 61  88 115]]

 [[ 18  33  59]
  [ 16  31  57]
  [ 15  30  56]
  ...
  [ 62  89 116]
  [ 66  93 120]
  [ 63  90 117]]

 [[ 19  34  60]
  [ 18  33  59]
  [ 16  31  57]
  ...
  [ 61  88 115]
  [ 66  93 120]
  [ 65  92 119]]

 ...

 [[ 36  62  76]
  [ 38  64  78]
  [ 34  60  74]
  ...
  [ 66 101 114]
  [ 67 102 115]
  [ 69 104 117]]

 [[ 31  57  71]
  [ 34  60  74]
  [ 32  58  72]
  ...
  [ 64  99 112]
  [ 66 101 114]
  [ 66 101 114]]

 [[ 36  62  76]
  [ 42  68  82]
  [ 41  67  81]
  ...
  [ 68 103 116]
  [ 71 106 119]
  [ 71 106 119]]]
